name: forklift_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  cross_file: ^0.3.3
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  upgrader: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
